version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  flask_app:
    image: my_flask_simple_app:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "9995:9995"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_APP=app_client.py
    depends_on:
      - redis

volumes:
  redis-data:
