apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9995
      targetPort: 9995
  clusterIP: None  # Headless service for direct pod access